import { createSlice } from '@reduxjs/toolkit';

const initialState = [
  { id: "1",
     title: "Dune",
     url:"https://th.bing.com/th/id/R.e1c0fac5a39f3129a536489ecba7eff6?rik=hwCFEryifOLFDw&pid=ImgRaw&r=0",
     author: "Frank Herbert",
     category: "Sci-Fi",
     description: "Dune by Frank Herbert is a landmark science fiction novel set in the distant future on the desert planet of Arrakis. The story follows Paul Atreides, a young nobleman whose family is entrusted with ruling Arrakis, the only source of the valuable spice melange. After his family is betrayed, Paul must navigate a world of political intrigue and harsh survival while uncovering his destiny as a messianic figure. Themes of power, religion, ecology, and human nature are explored in this epic tale of politics, prophecy, and survival.",
     rating: "4.5" },
  { id: "2",
     title: "1984", 
     url:"https://th.bing.com/th/id/OIP.8bTpGDLEYVpDlV8tD10XlQAAAA?rs=1&pid=ImgDetMain",
     author: "George Orwell", 
     category: "Fiction",
     description: "1984 by George Orwell is a dystopian novel set in a totalitarian society controlled by Big Brother, where the government monitors and controls every aspect of life. The story follows Winston Smith, a worker at the Ministry of Truth, who secretly rebels against the oppressive regime by starting a forbidden love affair and questioning the reality imposed by the government. Themes of surveillance, censorship, and the loss of individuality are explored in this chilling critique of authoritarianism and political manipulation.", 
     rating: "4.6" },
  { id: "3",
     title: "The Great Gatsby",
     url:"https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781471173936/the-great-gatsby-9781471173936_hr.jpg",
     author: "F. Scott Fitzgerald", 
     category: "Fiction", 
     description: "The Great Gatsby by F. Scott Fitzgerald is a classic novel set in the 1920s, exploring themes of wealth, love, and the American Dream. The story is narrated by Nick Carraway, who moves to Long Island and becomes entangled in the extravagant world of his mysterious neighbor, Jay Gatsby. Gatsby, a wealthy and enigmatic man, is obsessed with rekindling a past romance with Daisy Buchanan, a woman who is married to the wealthy but discontented Tom. The novel explores the moral decay and the illusion of happiness in the pursuit of wealth, as well as the tragic consequences of unattainable dreams.",
     rating: "4.2" },
  { id: "4", 
     title: "Charlotte's Web",
     url:"https://www.artkandy.com/cdn/shop/products/Charlotte_prev.jpg?v=1351757391",
     author: "E.B. White",
     category: "Fiction",
     description: "Charlotte's Web by E.B. White is a beloved children's novel that tells the story of a young pig named Wilbur and his unlikely friendship with Charlotte, a kind and intelligent spider. When Wilbur is in danger of being slaughtered, Charlotte spins messages in her web, such as Some Pig and Terrific, to convince the farmer and others that he is special and worth saving. Through themes of friendship, loyalty, and selflessness, the book teaches important lessons about life, love, and the inevitability of change. It's a heartwarming tale of friendship and sacrifice that has touched readers of all ages.",
     rating: "4.3" },
  { id: "5",
     title: "Wonder",
     url:"https://www.cadillaclibrary.org/book-groups/kids-book-groups/kids-book-club-images/wonder.jpg/@@images/bf225126-2082-4a11-beca-803c800755b2.jpeg",
     author: "R.J. Palacio",
     category: "Fiction",
     description: "Wonder by R.J. Palacio is a heartfelt novel about August Auggie Pullman, a young boy born with a facial deformity who is about to start school for the first time at the age of ten. The story follows Auggie's journey as he faces the challenges of being different, trying to fit in, and making friends, all while dealing with the judgment and prejudice of others. Told from multiple perspectives, the novel highlights themes of kindness, empathy, and the importance of looking beyond outward appearances. Wonder is a moving story about accepting others and oneself, and it encourages readers to be kind, especially in the face of adversity.",
     rating: "4.4" },
  { id: "6", 
     title: "Nancy Drew Series", 
     url:"https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781534463127/nancy-drew-files-vol-i-9781534463127_hr.jpg",
     author: "Carolyn Keene", 
     category: "Mystery", 
     description: "The Nancy Drew series, created by Carolyn Keene, is a long-running collection of mystery novels featuring the adventurous teenage detective Nancy Drew. First published in 1930, the series follows Nancy, a smart and resourceful young woman, as she solves a variety of mysteries, ranging from missing persons and stolen treasures to strange occurrences and local crimes.",
     rating: "4.1" },
  { id: "7", 
     title: "The Westing Game",
     url:"https://th.bing.com/th/id/OIP.gtYXZGpIGbcTJg3Z_xlJ_gHaKw?rs=1&pid=ImgDetMain", 
     author: "Ellen Raskin", 
     category: "Mystery",
     description: "The Westing Game by Ellen Raskin is a captivating mystery novel centered around the mysterious death of the wealthy and eccentric businessman Sam Westing. In his will, Westing leaves behind a challenge for sixteen heirs, who are brought together in a large, upscale apartment building. The heirs must work together (or against each other) to solve a complex puzzle in order to inherit his fortune.",
     rating: "4.5" },
  { id: "8", 
     title: "A Wrinkle in Time",
     url:"https://th.bing.com/th/id/R.f7527024ded7b127567f8a442b5ce904?rik=56zunbSSYqcJYQ&riu=http%3a%2f%2fimages.macmillan.com%2ffolio-assets%2fmacmillan_us_frontbookcovers_1000H%2f9780312367558.jpg&ehk=a20BHF4m6fxH8Pj7DwjWwnb7QFzLcMCidtovF9oSg8M%3d&risl=&pid=ImgRaw&r=0",
     author: "Madeleine L’Engle",
     category: "Sci-Fi", 
     description: "A Wrinkle in Time by Madeleine L'Engle is a science fiction novel that follows Meg Murry, her brother Charles Wallace, and their friend Calvin O'Keefe as they embark on a thrilling journey through space and time to rescue Meg’s father, who has been trapped on a distant planet by an evil force called IT. With the help of three mysterious beings—Mrs. Whatsit, Mrs. Which, and Mrs. Who—the trio travels through a wrinkle in time to otherworldly places.",
     rating: "4.3" },
  { id: "9",
     title: "The Last Kids on Earth",
     url:"https://cdn.kobo.com/book-images/7a421b01-bf66-42f2-ba9f-03e77abd45ed/1200/1200/False/the-last-kids-on-earth-1.jpg",
     author: "Max Brallier", 
     category: "Sci-Fi",
     description: "The Last Kids on Earth by Max Brallier is the first book in a thrilling series that combines adventure, humor, and post-apocalyptic survival. The story follows Jack Sullivan, a 13-year-old boy who, along with his friends Quint, Dirk, and June, is one of the few survivors in a world overrun by monsters and zombies. The group lives in a fortified treehouse, where they spend their time fighting off creatures, scavenging for supplies, and trying to have some fun despite the chaos around them.",
     rating: "4.0" },
  { id: "10",
     title: "Hidden Figures",
     url:"https://cdn.kobo.com/book-images/1c27071e-f8fd-4f54-a0be-312457f77223/1200/1200/False/hidden-figures.jpg", 
     author: "Margot Lee Shetterly", 
     category: "Non-Fiction",
     description: "Hidden Figures by Margot Lee Shetterly tells the inspiring true story of three African-American women—Katherine Johnson, Dorothy Vaughan, and Mary Jackson—who played crucial roles in the early years of NASA and the space race. Set in the 1950s and 60s, the book focuses on their groundbreaking work as mathematicians and engineers at a time when segregation and gender discrimination were prevalent in the workplace.",
     rating: "4.7" },
  { id: "11", 
     title: "Brown Girl Dreaming", 
     url:"https://th.bing.com/th/id/R.7536d8c90ee33c2d6ab7577f40331ad0?rik=rfFC0SamLw6yKA&riu=http%3a%2f%2fsmithsonianapa.org%2fbookdragon%2fwp-content%2fuploads%2fsites%2f10%2f2014%2f09%2fbrown-girl-dreaming.jpg&ehk=fIiBRI%2bJTcFobLW%2bjZjYjtnPseMwacJU%2fGGkQEGuvQk%3d&risl=&pid=ImgRaw&r=0",
     author: "Jacqueline Woodson",
     category: "Non-Fiction", 
     description: "Brown Girl Dreaming by Jacqueline Woodson is a memoir-in-verse that chronicles the author's childhood and coming-of-age experiences as an African American girl growing up in the 1960s and 70s. Told through a series of poetic reflections, the book explores Woodson's life in South Carolina and Brooklyn, focusing on themes of race, identity, family, and the power of storytelling.", 
     rating: "4.6" },
  { id: "12", 
     title: "The Immortal Life of Henrietta Lacks",
     url:"https://i5.walmartimages.com/asr/4950115d-fb74-478c-81aa-f6d5fe8a0367_1.1da422e879b679447b3a4f59a4368d10.jpeg",
     author: "Rebecca Skloot",
     category: "Non-Fiction",
     description: "The Immortal Life of Henrietta Lacks by Rebecca Skloot is a bestselling non-fiction book that tells the extraordinary true story of Henrietta Lacks, an African American woman whose cancer cells, taken without her knowledge in 1951, became one of the most important tools in medical research. Known as HeLa cells, they were the first human cells to survive and multiply outside the body, leading to major breakthroughs in medicine, including the development of the polio vaccine, cancer treatments, and in vitro fertilization.",
     rating: "4.5" },
  { id: "13",
     title: "Becoming", 
     url:"https://th.bing.com/th/id/OIP.e__NEYvJpiqMPy4lAR_zHgHaLQ?rs=1&pid=ImgDetMain",
     author: "Michelle Obama", 
     category: "Non-Fiction",
     description: "Becoming by Michelle Obama is a deeply personal memoir by the former First Lady of the United States. In the book, Michelle shares the story of her life, from her childhood on the South Side of Chicago, through her education at Princeton and Harvard Law School, to her career as a lawyer and public servant, and finally, her years in the White House alongside her husband, President Barack Obama.", 
     rating: "4.8" },
  { id: "14", 
     title: "Murder on the Orient Express",
     url:"https://i.harperapps.com/hcuk/covers/9780008255459/x800.JPG",
     author: "Agatha Christie",
     category: "Mystery",
     description: "Murder on the Orient Express by Agatha Christie is a classic mystery novel featuring the famous detective Hercule Poirot. Set aboard the luxurious Orient Express train traveling from Istanbul to Calais, the story begins when a wealthy American passenger, Samuel Ratchett, is found murdered in his compartment.", 
     rating: "4.4" },
  { id: "15", 
     title: "The Maltese Falcon",
     url:"https://cdn11.bigcommerce.com/s-gibnfyxosi/images/stencil/1280x1280/products/107746/109518/51kDq26MsEL__98268.1615557211.jpg?c=1",
     author: "Dashiell Hammett",
     category: "Mystery", 
     description: "The Maltese Falcon by Dashiell Hammett is a classic hard-boiled detective novel first published in 1930. It follows private detective Sam Spade as he becomes entangled in a dangerous search for a priceless, jewel-encrusted statue known as the Maltese Falcon.",
     rating: "4.3" },
  { id: "16", 
     title: "Gone Girl", 
     url:"https://th.bing.com/th/id/R.979b1d14087153c5e264fef39aee3a96?rik=ADYwTpdpf0DeqQ&riu=http%3a%2f%2fimages6.fanpop.com%2fimage%2fphotos%2f37400000%2fGone-Girl-by-Gillian-Flynn-gone-girl-37441442-1181-1810.jpg&ehk=rtg5qz7Eh5WgcMzc%2bCEMz7DThMzsLhAX39DPt%2fl9MtM%3d&risl=&pid=ImgRaw&r=0",
     author: "Gillian Flynn", 
     category: "Mystery",
     description: "Gone Girl by Gillian Flynn is a psychological thriller that tells the story of Nick and Amy Dunne, a seemingly perfect couple whose marriage takes a dark turn. On their fifth wedding anniversary, Amy mysteriously disappears, and as the investigation unfolds, suspicion quickly falls on Nick.", 
     rating: "4.6" },
];

const booksSlice = createSlice({
  name: 'books',
  initialState,
  reducers: {
    addBook: (state, action) => {
      state.push(action.payload);
    },
  },
});

export const { addBook } = booksSlice.actions;
export default booksSlice.reducer;
